- name: Markdown-HTML
  uses: ZacJW/markdown-html-action@1.1.1
  with:
    input_files: '[["README.md"]]'
    output_files: '["index.html"]'
    stylesheet_url: 'https://raw.githubusercontent.com/您的用户名/您的仓库名/main/templates/style.css'
    template: 'https://raw.githubusercontent.com/您的用户名/您的仓库名/main/templates/template.html'
