name: CI2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: PRINT-ENV
        run: printenv

      - name: Markdown-HTML-ACTION
        uses: ZacJW/markdown-html-action@1.1.1
        with:
          input_files: '[["README.md"]]'
          output_files: '["index.bkp.html"]'
          template: '["template.html"]'
          builtin_stylesheet: 'style.css'

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GITHUB ACTION'
          default_author: user_info
          message: 'Generate html files from readme.'
          pathspec_error_handling: exitImmediately

